// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
import {IGovernanceCore, IPayloadsControllerCore, IDataWarehouse, IVotingStrategy} from './GovernanceV3.sol';
library GovernanceV3Sepolia {
  // https://sepolia.etherscan.io/address/0xF57D158aA44B95E657bA4697fD69A2B9037bd723
  address internal constant CROSS_CHAIN_CONTROLLER = 0xF57D158aA44B95E657bA4697fD69A2B9037bd723;

  // https://sepolia.etherscan.io/address/0x2B2fa1A67964613F8056FB8612494893A2B90DCa
  IGovernanceCore internal constant GOVERNANCE =
    IGovernanceCore(0x2B2fa1A67964613F8056FB8612494893A2B90DCa);

  // https://sepolia.etherscan.io/address/0x0c8B7355c0d048B1ce74FDE2D638415D5a392Ac7
  address internal constant VOTING_MACHINE = 0x0c8B7355c0d048B1ce74FDE2D638415D5a392Ac7;

  // https://sepolia.etherscan.io/address/0xF3a4C3BDa8d54971aA5cEbdeF3326d9ea4Fd8262
  IPayloadsControllerCore internal constant PAYLOADS_CONTROLLER =
    IPayloadsControllerCore(0xF3a4C3BDa8d54971aA5cEbdeF3326d9ea4Fd8262);

  // https://sepolia.etherscan.io/address/0x86224d188f4005d5De75eEeFfC45dE51d3A4969c
  address internal constant VOTING_PORTAL_ETH_ETH = 0x86224d188f4005d5De75eEeFfC45dE51d3A4969c;

  // https://sepolia.etherscan.io/address/0x2c2585E30c1CC1F0B4f4992F17957E31C9750983
  address internal constant VOTING_PORTAL_ETH_AVAX = 0x2c2585E30c1CC1F0B4f4992F17957E31C9750983;

  // https://sepolia.etherscan.io/address/0x31a1517c21fA41b7c4A208379a3f988093E4Aa44
  address internal constant VOTING_PORTAL_ETH_POL = 0x31a1517c21fA41b7c4A208379a3f988093E4Aa44;

  // https://sepolia.etherscan.io/address/0x318B3A669156f530EB997495d015830E3bc3Ff9F
  address internal constant GOVERNANCE_POWER_STRATEGY = 0x318B3A669156f530EB997495d015830E3bc3Ff9F;

  // https://sepolia.etherscan.io/address/0x4EbD93aC31089591aDf9b752117128a66c14B28b
  address internal constant EXECUTOR_LVL_1 = 0x4EbD93aC31089591aDf9b752117128a66c14B28b;

  // https://sepolia.etherscan.io/address/0xf327D3fac973e9C6744CB2CCF73187aFC36AeA55
  address internal constant EXECUTOR_LVL_2 = 0xf327D3fac973e9C6744CB2CCF73187aFC36AeA55;

  // https://sepolia.etherscan.io/address/0x90021Ca340adCFa213af9A3BfC1b0dD38c01FCd9
  IVotingStrategy internal constant VOTING_STRATEGY =
    IVotingStrategy(0x90021Ca340adCFa213af9A3BfC1b0dD38c01FCd9);

  // https://sepolia.etherscan.io/address/0xD6480B403B9b2C48c4fbF15F6120b6f1F1b04496
  IDataWarehouse internal constant DATA_WAREHOUSE =
    IDataWarehouse(0xD6480B403B9b2C48c4fbF15F6120b6f1F1b04496);
}
