// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library ProtocolSafetyModuleSepolia {
  // https://sepolia.etherscan.io/address/0x234753D2Cc86a6Ee8d895caEA93A89c048d987Eb
  address internal constant STK_AAVE = 0x234753D2Cc86a6Ee8d895caEA93A89c048d987Eb;
}
