// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library ProtocolSafetyModule {
  // https://etherscan.io/address/0x4da27a545c0c5B758a6BA100e3a049001de870f5
  address internal constant STK_AAVE = 0x4da27a545c0c5B758a6BA100e3a049001de870f5;
}
