// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './ProtocolV3.sol';
import {ICollector} from './common/ICollector.sol';
library ProtocolV3Sepolia {
  // https://sepolia.etherscan.io/address/0xb15f57A3fc61c56CFDBBda904E8366A9244387ae
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xb15f57A3fc61c56CFDBBda904E8366A9244387ae);

  // https://sepolia.etherscan.io/address/0x9F0733Fb55104029F5955C5484B3f9AAD46f735B
  IPool internal constant POOL = IPool(0x9F0733Fb55104029F5955C5484B3f9AAD46f735B);

  // https://sepolia.etherscan.io/address/0x96Ac0307641D69e7F7A10E449D9EE98De09146b7
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x96Ac0307641D69e7F7A10E449D9EE98De09146b7);

  // https://sepolia.etherscan.io/address/0x9d93EB205f1474C97f08B3003e659d4A059dFFEf
  IAaveOracle internal constant ORACLE = IAaveOracle(0x9d93EB205f1474C97f08B3003e659d4A059dFFEf);

  // https://sepolia.etherscan.io/address/0x0b6d901Ed06FE8f3f24d7E4F49597B320f5dCA6b
  address internal constant ACL_ADMIN = 0x0b6d901Ed06FE8f3f24d7E4F49597B320f5dCA6b;

  // https://sepolia.etherscan.io/address/0x27325C299B4F3E42c565d3D5EE53761C6e1b18D8
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x27325C299B4F3E42c565d3D5EE53761C6e1b18D8);

  // https://sepolia.etherscan.io/address/0x7496B2187F8Ec804C4aD78d10E4F009C0896C550
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x7496B2187F8Ec804C4aD78d10E4F009C0896C550);

  // https://sepolia.etherscan.io/address/0x88CD1dB85E3fc9606da97a897098c732F98dc3D3
  address internal constant POOL_IMPL = 0x88CD1dB85E3fc9606da97a897098c732F98dc3D3;

  // https://sepolia.etherscan.io/address/0x093c5816b366D2f96e34118860205A156e31cc36
  address internal constant POOL_CONFIGURATOR_IMPL = 0x093c5816b366D2f96e34118860205A156e31cc36;

  // https://sepolia.etherscan.io/address/0x905628d218D76E7668F63718f47c7C4b45a31B75
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x905628d218D76E7668F63718f47c7C4b45a31B75;

  // https://sepolia.etherscan.io/address/0x39e653Db7197378bf4a026D71CFB50864d6a3C24
  address internal constant EMISSION_MANAGER = 0x39e653Db7197378bf4a026D71CFB50864d6a3C24;

  // https://sepolia.etherscan.io/address/0xeac57191Eb7A89f7Fd9B1B6bc0683e5751bD9f13
  ICollector internal constant COLLECTOR = ICollector(0xeac57191Eb7A89f7Fd9B1B6bc0683e5751bD9f13);

  // https://sepolia.etherscan.io/address/0xC646cf5FC66769bD02556020E15Fe374DdB97d47
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xC646cf5FC66769bD02556020E15Fe374DdB97d47;

  // https://sepolia.etherscan.io/address/0x7Fc643429eC9364BF404FE630d746D8f791ea604
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x7Fc643429eC9364BF404FE630d746D8f791ea604;

  // https://sepolia.etherscan.io/address/0x4Fdb06226d0F39000CC6D4c2A8cdFbD1513b8B94
  address internal constant FAUCET = 0x4Fdb06226d0F39000CC6D4c2A8cdFbD1513b8B94;

  // https://sepolia.etherscan.io/address/0xFF73A10D4E3bc679ee1434Ab6C9a0E18f978Ac79
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xFF73A10D4E3bc679ee1434Ab6C9a0E18f978Ac79;

  // https://sepolia.etherscan.io/address/0x4bf099cfa6e081707b287B5F97a4982995d16f5d
  address internal constant UI_POOL_DATA_PROVIDER = 0x4bf099cfa6e081707b287B5F97a4982995d16f5d;

  // https://sepolia.etherscan.io/address/0x3d02cc698eF5AcE5aA191d93C3BCa459e9268C7e
  address internal constant WALLET_BALANCE_PROVIDER = 0x3d02cc698eF5AcE5aA191d93C3BCa459e9268C7e;

  // https://sepolia.etherscan.io/address/0xfc6E0407a6eBaf1C74E617BDE3b8B764E58c5ac3
  address internal constant WETH_GATEWAY = 0xfc6E0407a6eBaf1C74E617BDE3b8B764E58c5ac3;
}
library ProtocolV3SepoliaAssets {
  // https://sepolia.etherscan.io/address/0x8D43bd5be0eFA0496F5C797ee2196b5C791717e0
  address internal constant DAI_UNDERLYING = 0x8D43bd5be0eFA0496F5C797ee2196b5C791717e0;

  uint8 internal constant DAI_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x159D4790CF2d6d7b4fB72d75e85db40bD265718e
  address internal constant DAI_A_TOKEN = 0x159D4790CF2d6d7b4fB72d75e85db40bD265718e;

  // https://sepolia.etherscan.io/address/0x36c8393EeaB33829f943c9688C17daE654AAbBB0
  address internal constant DAI_V_TOKEN = 0x36c8393EeaB33829f943c9688C17daE654AAbBB0;

  // https://sepolia.etherscan.io/address/0xeEd3e03a63831b4B2243cD9A88996315E7D243A3
  address internal constant DAI_ORACLE = 0xeEd3e03a63831b4B2243cD9A88996315E7D243A3;

  // https://sepolia.etherscan.io/address/0xbE6537eFa8B753Ed395d4bB37CCA72a12be1d711
  address internal constant DAI_INTEREST_RATE_STRATEGY = 0xbE6537eFa8B753Ed395d4bB37CCA72a12be1d711;

  // https://sepolia.etherscan.io/address/0x36F9bc47E06Cd4eEAD1E740c0c44E74895a459D5
  address internal constant LINK_UNDERLYING = 0x36F9bc47E06Cd4eEAD1E740c0c44E74895a459D5;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0xd66f1AF43395Fc678CA275b853499B6d91cDB4A5
  address internal constant LINK_A_TOKEN = 0xd66f1AF43395Fc678CA275b853499B6d91cDB4A5;

  // https://sepolia.etherscan.io/address/0x1e13211F6C63B85f36Ce9AEC48112cC4dd4562CC
  address internal constant LINK_V_TOKEN = 0x1e13211F6C63B85f36Ce9AEC48112cC4dd4562CC;

  // https://sepolia.etherscan.io/address/0xa2450080d354346034d626227bec56b517ca76c2
  address internal constant LINK_ORACLE = 0xa2450080d354346034d626227bec56b517ca76c2;

  // https://sepolia.etherscan.io/address/0x52895205F03063BA3F515178c0F004cAfF6C22b1
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0x52895205F03063BA3F515178c0F004cAfF6C22b1;

  // https://sepolia.etherscan.io/address/0xad150b97be2E19FCae53f98938eEEFb2B400be00
  address internal constant USDC_UNDERLYING = 0xad150b97be2E19FCae53f98938eEEFb2B400be00;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://sepolia.etherscan.io/address/0xcA92a4eBEfC17A68C9ec85F0A4aaA44b7f8D2338
  address internal constant USDC_A_TOKEN = 0xcA92a4eBEfC17A68C9ec85F0A4aaA44b7f8D2338;

  // https://sepolia.etherscan.io/address/0x3D76de1054d2EDce99B8A7366257e0D8C6ace323
  address internal constant USDC_V_TOKEN = 0x3D76de1054d2EDce99B8A7366257e0D8C6ace323;

  // https://sepolia.etherscan.io/address/0x69B175E24a37ab245A72859DEC22dedaD29bEc55
  address internal constant USDC_ORACLE = 0x69B175E24a37ab245A72859DEC22dedaD29bEc55;

  // https://sepolia.etherscan.io/address/0xD57b5c31f0d085592F7642B2A3cECF6C9f41897C
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0xD57b5c31f0d085592F7642B2A3cECF6C9f41897C;

  // https://sepolia.etherscan.io/address/0xa7aD3209558042AE0E2D8ec326c7D24b3c13FeA7
  address internal constant WBTC_UNDERLYING = 0xa7aD3209558042AE0E2D8ec326c7D24b3c13FeA7;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://sepolia.etherscan.io/address/0xeE01e0B110988818364971A4c94B7bFE14A1f984
  address internal constant WBTC_A_TOKEN = 0xeE01e0B110988818364971A4c94B7bFE14A1f984;

  // https://sepolia.etherscan.io/address/0x2048ce94F628a6fC553A59b7788C46a56E58d26B
  address internal constant WBTC_V_TOKEN = 0x2048ce94F628a6fC553A59b7788C46a56E58d26B;

  // https://sepolia.etherscan.io/address/0x4c36faEef8CdD219E2A0aaDF8962BEc6BB589D82
  address internal constant WBTC_ORACLE = 0x4c36faEef8CdD219E2A0aaDF8962BEc6BB589D82;

  // https://sepolia.etherscan.io/address/0x52895205F03063BA3F515178c0F004cAfF6C22b1
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x52895205F03063BA3F515178c0F004cAfF6C22b1;

  // https://sepolia.etherscan.io/address/0xbd546A644409e9259C489Dae318A5F3291CB1567
  address internal constant WETH_UNDERLYING = 0xbd546A644409e9259C489Dae318A5F3291CB1567;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x093410C9C48214c0132B02f006b4a5b8FFA9aaAC
  address internal constant WETH_A_TOKEN = 0x093410C9C48214c0132B02f006b4a5b8FFA9aaAC;

  // https://sepolia.etherscan.io/address/0xd0D7252Acf17340c897352cf1D5E30Bc38419b32
  address internal constant WETH_V_TOKEN = 0xd0D7252Acf17340c897352cf1D5E30Bc38419b32;

  // https://sepolia.etherscan.io/address/0xb78f17CEFd8A3dB259F584a1FB36854744BC06F2
  address internal constant WETH_ORACLE = 0xb78f17CEFd8A3dB259F584a1FB36854744BC06F2;

  // https://sepolia.etherscan.io/address/0x52895205F03063BA3F515178c0F004cAfF6C22b1
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x52895205F03063BA3F515178c0F004cAfF6C22b1;

  // https://sepolia.etherscan.io/address/0xf9AAC7D5040B0935a29e7a62438cd8f152BdA624
  address internal constant USDT_UNDERLYING = 0xf9AAC7D5040B0935a29e7a62438cd8f152BdA624;

  uint8 internal constant USDT_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0x28c3C811F30A12d83A624D6F47680353BD1dc2fD
  address internal constant USDT_A_TOKEN = 0x28c3C811F30A12d83A624D6F47680353BD1dc2fD;

  // https://sepolia.etherscan.io/address/0xd9F3d2b92FCE7777799ed85E4217Ee23c4A75eC9
  address internal constant USDT_V_TOKEN = 0xd9F3d2b92FCE7777799ed85E4217Ee23c4A75eC9;

  // https://sepolia.etherscan.io/address/0x75DB2B1973664Eb3861BaC26E4C536311D028b6b
  address internal constant USDT_ORACLE = 0x75DB2B1973664Eb3861BaC26E4C536311D028b6b;

  // https://sepolia.etherscan.io/address/0xD57b5c31f0d085592F7642B2A3cECF6C9f41897C
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0xD57b5c31f0d085592F7642B2A3cECF6C9f41897C;

  // https://sepolia.etherscan.io/address/0x46A69C9C2c123d3A4947c18AbA031EB41409FaDa
  address internal constant AAVE_UNDERLYING = 0x46A69C9C2c123d3A4947c18AbA031EB41409FaDa;

  uint8 internal constant AAVE_DECIMALS = 18;

  // https://sepolia.etherscan.io/address/0xF5AA3E1e6deAF69B90884266126c4EB18F5EcE64
  address internal constant AAVE_A_TOKEN = 0xF5AA3E1e6deAF69B90884266126c4EB18F5EcE64;

  // https://sepolia.etherscan.io/address/0x31b7769eB5336463898EAc876d2383A2e30CDE15
  address internal constant AAVE_V_TOKEN = 0x31b7769eB5336463898EAc876d2383A2e30CDE15;

  // https://sepolia.etherscan.io/address/0x2daE65A4B86B0f4832861a950c87957b8CA2e4FF
  address internal constant AAVE_ORACLE = 0x2daE65A4B86B0f4832861a950c87957b8CA2e4FF;

  // https://sepolia.etherscan.io/address/0x52895205F03063BA3F515178c0F004cAfF6C22b1
  address internal constant AAVE_INTEREST_RATE_STRATEGY =
    0x52895205F03063BA3F515178c0F004cAfF6C22b1;

  // https://sepolia.etherscan.io/address/0x5f8B03fF805DdFe9A9549385b841Af26121f8871
  address internal constant EURS_UNDERLYING = 0x5f8B03fF805DdFe9A9549385b841Af26121f8871;

  uint8 internal constant EURS_DECIMALS = 2;

  // https://sepolia.etherscan.io/address/0x95d696832615Ba780204d3C0699cb214889598d8
  address internal constant EURS_A_TOKEN = 0x95d696832615Ba780204d3C0699cb214889598d8;

  // https://sepolia.etherscan.io/address/0xae5779e52D349512f5C27783aB6F220D34aC3715
  address internal constant EURS_V_TOKEN = 0xae5779e52D349512f5C27783aB6F220D34aC3715;

  // https://sepolia.etherscan.io/address/0x906275252cfe7d290B896C3BA8c91aBFA56c0FA3
  address internal constant EURS_ORACLE = 0x906275252cfe7d290B896C3BA8c91aBFA56c0FA3;

  // https://sepolia.etherscan.io/address/0xD57b5c31f0d085592F7642B2A3cECF6C9f41897C
  address internal constant EURS_INTEREST_RATE_STRATEGY =
    0xD57b5c31f0d085592F7642B2A3cECF6C9f41897C;
}
