// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './ProtocolV3.sol';
import {ICollector} from './common/ICollector.sol';
library ProtocolV3Ethereum {
  // https://etherscan.io/address/0x7c8D27Bc0581033DdC33D26470B212Ee20c5327b
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x7c8D27Bc0581033DdC33D26470B212Ee20c5327b);

  // https://etherscan.io/address/0x5aebD160b702fb4efbaDcedf55673a96366fa594
  IPool internal constant POOL = IPool(0x5aebD160b702fb4efbaDcedf55673a96366fa594);

  // https://etherscan.io/address/0xd1a7c962B1ec936ed37d6065142AFf78e24978bE
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xd1a7c962B1ec936ed37d6065142AFf78e24978bE);

  // https://etherscan.io/address/0xE27E5C9102922b41E3fF2541012f41BED7A2F16a
  IAaveOracle internal constant ORACLE = IAaveOracle(0xE27E5C9102922b41E3fF2541012f41BED7A2F16a);

  // https://etherscan.io/address/0x084126414188735846e4f1851cB3d01D829Fa15b
  address internal constant ACL_ADMIN = 0x084126414188735846e4f1851cB3d01D829Fa15b;

  // https://etherscan.io/address/0xee6334FAE1C6a64BCA58b2B15Fe0C7a2705E8f05
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xee6334FAE1C6a64BCA58b2B15Fe0C7a2705E8f05);

  // https://etherscan.io/address/0x4719499CD6832EB47d9073884579d66f8bb43407
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x4719499CD6832EB47d9073884579d66f8bb43407);

  // https://etherscan.io/address/0xdD666Dbcb0635E06806C6C19Fc9442cb0F202308
  address internal constant POOL_IMPL = 0xdD666Dbcb0635E06806C6C19Fc9442cb0F202308;

  // https://etherscan.io/address/0x61b3506fAe8726d8de1890abD2b6abB3006A2013
  address internal constant POOL_CONFIGURATOR_IMPL = 0x61b3506fAe8726d8de1890abD2b6abB3006A2013;

  // https://etherscan.io/address/0xD1AC9db961bF41E52847DE85E811c26c63f59bB6
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0xD1AC9db961bF41E52847DE85E811c26c63f59bB6;

  // https://etherscan.io/address/0x71cE5b1e07483cc59FFA329828dec8a98a3d2E1D
  address internal constant EMISSION_MANAGER = 0x71cE5b1e07483cc59FFA329828dec8a98a3d2E1D;

  // https://etherscan.io/address/0x5577B156C3ad7beC2A11BBe29009B330ac5C9bF5
  ICollector internal constant COLLECTOR = ICollector(0x5577B156C3ad7beC2A11BBe29009B330ac5C9bF5);

  // https://etherscan.io/address/0xf6fAb4510DF36E263F2b451054f427c6C128b41D
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xf6fAb4510DF36E263F2b451054f427c6C128b41D;

  // https://etherscan.io/address/0xaCC554dd20DEBcdA9d5633a0a664957860eBF3cF
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xaCC554dd20DEBcdA9d5633a0a664957860eBF3cF;

  // https://etherscan.io/address/0x82dcCF206Ae2Ab46E2099e663F70DeE77caE7778
  address internal constant CAPS_PLUS_RISK_STEWARD = 0x82dcCF206Ae2Ab46E2099e663F70DeE77caE7778;

  // https://etherscan.io/address/0x7C7143f4bE189928A6a98D8686c5e84c893c59c7
  address internal constant RISK_STEWARD = 0x7C7143f4bE189928A6a98D8686c5e84c893c59c7;

  // https://etherscan.io/address/0x2eE68ACb6A1319de1b49DC139894644E424fefD6
  address internal constant FREEZING_STEWARD = 0x2eE68ACb6A1319de1b49DC139894644E424fefD6;

  // https://etherscan.io/address/0xd7852E139a7097E119623de0751AE53a61efb442
  address internal constant DEBT_SWAP_ADAPTER = 0xd7852E139a7097E119623de0751AE53a61efb442;

  // https://etherscan.io/address/0xA8e351C7Ab1b75A2134A418701919c462932DF79
  address internal constant CONFIG_ENGINE = 0xA8e351C7Ab1b75A2134A418701919c462932DF79;

  // https://etherscan.io/address/0xC172E77E96E06b7243f62996D218A9e0b013a478
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0xC172E77E96E06b7243f62996D218A9e0b013a478;

  // https://etherscan.io/address/0x411D79b8cC43384FDE66CaBf9b6a17180c842511
  address internal constant STATIC_A_TOKEN_FACTORY = 0x411D79b8cC43384FDE66CaBf9b6a17180c842511;

  // https://etherscan.io/address/0xa7aD3209558042AE0E2D8ec326c7D24b3c13FeA7
  address internal constant REPAY_WITH_COLLATERAL_ADAPTER =
    0xa7aD3209558042AE0E2D8ec326c7D24b3c13FeA7;

  // https://etherscan.io/address/0xad150b97be2E19FCae53f98938eEEFb2B400be00
  address internal constant SWAP_COLLATERAL_ADAPTER = 0xad150b97be2E19FCae53f98938eEEFb2B400be00;

  // https://etherscan.io/address/0x8D43bd5be0eFA0496F5C797ee2196b5C791717e0
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x8D43bd5be0eFA0496F5C797ee2196b5C791717e0;

  // https://etherscan.io/address/0x36F9bc47E06Cd4eEAD1E740c0c44E74895a459D5
  address internal constant UI_POOL_DATA_PROVIDER = 0x36F9bc47E06Cd4eEAD1E740c0c44E74895a459D5;

  // https://etherscan.io/address/0x4Fdb06226d0F39000CC6D4c2A8cdFbD1513b8B94
  address internal constant WALLET_BALANCE_PROVIDER = 0x4Fdb06226d0F39000CC6D4c2A8cdFbD1513b8B94;

  // https://etherscan.io/address/0xf6311E010C17e10f1258E5e67346d9f615D467f1
  address internal constant WETH_GATEWAY = 0xf6311E010C17e10f1258E5e67346d9f615D467f1;

  // https://etherscan.io/address/0xbd546A644409e9259C489Dae318A5F3291CB1567
  address internal constant WITHDRAW_SWAP_ADAPTER = 0xbd546A644409e9259C489Dae318A5F3291CB1567;

  // https://etherscan.io/address/0xc4D386d294f9b08AF4DC102a6E43dDd3Dd566df8
  address internal constant DELEGATION_AWARE_A_TOKEN_IMPL_REV_1 =
    0xc4D386d294f9b08AF4DC102a6E43dDd3Dd566df8;
}
library ProtocolV3EthereumAssets {
  // https://etherscan.io/address/0x6B175474E89094C44Da98b954EedeAC495271d0F
  address internal constant DAI_UNDERLYING = 0x6B175474E89094C44Da98b954EedeAC495271d0F;

  uint8 internal constant DAI_DECIMALS = 18;

  // https://etherscan.io/address/0x15DD569996679a766E6f96f97Bf2f94336f85906
  address internal constant DAI_A_TOKEN = 0x15DD569996679a766E6f96f97Bf2f94336f85906;

  // https://etherscan.io/address/0x8E9359Ee5eF03be33943DBf44C8efA35586d5b25
  address internal constant DAI_V_TOKEN = 0x8E9359Ee5eF03be33943DBf44C8efA35586d5b25;

  // https://etherscan.io/address/0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9
  address internal constant DAI_ORACLE = 0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9;

  // https://etherscan.io/address/0x5F64941e9C7433AA778D057Ad3aB01102709dA9F
  address internal constant DAI_INTEREST_RATE_STRATEGY = 0x5F64941e9C7433AA778D057Ad3aB01102709dA9F;

  // https://etherscan.io/address/0xaf270C38fF895EA3f95Ed488CEACe2386F038249
  address internal constant DAI_STATIC_A_TOKEN = 0xaf270C38fF895EA3f95Ed488CEACe2386F038249;

  // https://etherscan.io/address/0x514910771AF9Ca656af840dff83E8264EcF986CA
  address internal constant LINK_UNDERLYING = 0x514910771AF9Ca656af840dff83E8264EcF986CA;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://etherscan.io/address/0x4a6901617a028a29c421DE4a995b0147030DcA0c
  address internal constant LINK_A_TOKEN = 0x4a6901617a028a29c421DE4a995b0147030DcA0c;

  // https://etherscan.io/address/0x4E531932FEf0DE2BC9514C20654cf10D686B9598
  address internal constant LINK_V_TOKEN = 0x4E531932FEf0DE2BC9514C20654cf10D686B9598;

  // https://etherscan.io/address/0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c
  address internal constant LINK_ORACLE = 0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c;

  // https://etherscan.io/address/0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C;

  // https://etherscan.io/address/0x57bd8C73838d1781b4f6E0d5Cf89eb676488d3df
  address internal constant LINK_STATIC_A_TOKEN = 0x57bd8C73838d1781b4f6E0d5Cf89eb676488d3df;

  // https://etherscan.io/address/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
  address internal constant USDC_UNDERLYING = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://etherscan.io/address/0xBF559FF3ED3e6E669c288D76a914100695AF69F4
  address internal constant USDC_A_TOKEN = 0xBF559FF3ED3e6E669c288D76a914100695AF69F4;

  // https://etherscan.io/address/0x3E282F120DBC78839EC0A1084810c33dF201D33D
  address internal constant USDC_V_TOKEN = 0x3E282F120DBC78839EC0A1084810c33dF201D33D;

  // https://etherscan.io/address/0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6
  address internal constant USDC_ORACLE = 0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6;

  // https://etherscan.io/address/0x4F67001f5AC4e83373C68F80111BD266f66eB027
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x4F67001f5AC4e83373C68F80111BD266f66eB027;

  // https://etherscan.io/address/0x73edDFa87C71ADdC275c2b9890f5c3a8480bC9E6
  address internal constant USDC_STATIC_A_TOKEN = 0x73edDFa87C71ADdC275c2b9890f5c3a8480bC9E6;

  // https://etherscan.io/address/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
  address internal constant WBTC_UNDERLYING = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://etherscan.io/address/0xf0684fb9539D0268BdFc47050f24153921FD7ebb
  address internal constant WBTC_A_TOKEN = 0xf0684fb9539D0268BdFc47050f24153921FD7ebb;

  // https://etherscan.io/address/0xb0c9998260F7d72d79fEC7A4AE775031c31090D1
  address internal constant WBTC_V_TOKEN = 0xb0c9998260F7d72d79fEC7A4AE775031c31090D1;

  // https://etherscan.io/address/0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c
  address internal constant WBTC_ORACLE = 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c;

  // https://etherscan.io/address/0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C;

  // https://etherscan.io/address/0xB07E357cc262E92eee03D8B81464D596B258eA7a
  address internal constant WBTC_STATIC_A_TOKEN = 0xB07E357cc262E92eee03D8B81464D596B258eA7a;

  // https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
  address internal constant WETH_UNDERLYING = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://etherscan.io/address/0x8C829396A0Adc89c17274c0AfC7dA705D7E4e1D9
  address internal constant WETH_A_TOKEN = 0x8C829396A0Adc89c17274c0AfC7dA705D7E4e1D9;

  // https://etherscan.io/address/0x30Ed3C528f824D894eE060a426D7Bc48CC55d863
  address internal constant WETH_V_TOKEN = 0x30Ed3C528f824D894eE060a426D7Bc48CC55d863;

  // https://etherscan.io/address/0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419
  address internal constant WETH_ORACLE = 0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419;

  // https://etherscan.io/address/0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C;

  // https://etherscan.io/address/0x252231882FB38481497f3C767469106297c8d93b
  address internal constant WETH_STATIC_A_TOKEN = 0x252231882FB38481497f3C767469106297c8d93b;

  // https://etherscan.io/address/0xdAC17F958D2ee523a2206206994597C13D831ec7
  address internal constant USDT_UNDERLYING = 0xdAC17F958D2ee523a2206206994597C13D831ec7;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://etherscan.io/address/0xBE4399DaB4fF2E7B2eBE50a45CC330FF4Bc95f64
  address internal constant USDT_A_TOKEN = 0xBE4399DaB4fF2E7B2eBE50a45CC330FF4Bc95f64;

  // https://etherscan.io/address/0xd7cb4dF4df26DCD6b70f710194a2BF13ebf2c020
  address internal constant USDT_V_TOKEN = 0xd7cb4dF4df26DCD6b70f710194a2BF13ebf2c020;

  // https://etherscan.io/address/0x3E7d1eAB13ad0104d2750B8863b489D65364e32D
  address internal constant USDT_ORACLE = 0x3E7d1eAB13ad0104d2750B8863b489D65364e32D;

  // https://etherscan.io/address/0x4F67001f5AC4e83373C68F80111BD266f66eB027
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x4F67001f5AC4e83373C68F80111BD266f66eB027;

  // https://etherscan.io/address/0x862c57d48becB45583AEbA3f489696D22466Ca1b
  address internal constant USDT_STATIC_A_TOKEN = 0x862c57d48becB45583AEbA3f489696D22466Ca1b;

  // https://etherscan.io/address/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9
  address internal constant AAVE_UNDERLYING = 0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9;

  uint8 internal constant AAVE_DECIMALS = 18;

  // https://etherscan.io/address/0x0e4dD12D36dBc5A251057AdB7bBC3a6C44d36a3a
  address internal constant AAVE_A_TOKEN = 0x0e4dD12D36dBc5A251057AdB7bBC3a6C44d36a3a;

  // https://etherscan.io/address/0x4450FC0eB292CaD008Cb7CBC7d3d2dfC5ACEFf99
  address internal constant AAVE_V_TOKEN = 0x4450FC0eB292CaD008Cb7CBC7d3d2dfC5ACEFf99;

  // https://etherscan.io/address/0x547a514d5e3769680Ce22B2361c10Ea13619e8a9
  address internal constant AAVE_ORACLE = 0x547a514d5e3769680Ce22B2361c10Ea13619e8a9;

  // https://etherscan.io/address/0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C
  address internal constant AAVE_INTEREST_RATE_STRATEGY =
    0x5971A1b65f2bB666a2ebE697c342b7eFD6f7FE6C;

  // https://etherscan.io/address/0xFEB859A50f92C6D5ad7C9eF7C2c060D164B3280f
  address internal constant AAVE_STATIC_A_TOKEN = 0xFEB859A50f92C6D5ad7C9eF7C2c060D164B3280f;
}
