// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library ProtocolSafetyModuleBNB {
  // https://bscscan.com/address/0x5F281bdaD2E6d4af7354054f48609273e874366f
  address internal constant STK_AAVE = 0x5F281bdaD2E6d4af7354054f48609273e874366f;
}
